on:
  push:
    paths:
      - 'frontend/**'
  pull_request:
    paths:
      - 'frontend/**'

permissions:
  contents: write
jobs:
  build_test:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '23.11'

    - name: Install frontend dependencies
      run: |
        cd frontend
        npm install

    - name: Format with Prettier
      run: |
        cd frontend
        npm run format

    - name: Commit Prettier changes
      run: |
        cd frontend
        git config --global user.name 'tomek-actions'
        git config --global user.email 'tomek-actions@github.com'
        git add .
        git diff --cached --quiet || git commit -m "chore: format code with Prettier"
        git push
      continue-on-error: true

    - name: Test frontend with coverage
      run: |
        cd frontend
        npm run coverage

    - name: Lint frontend
      run: |
        cd frontend
        npm run lint

    - name: Build frontend
      run: |
        cd frontend
        npm run build
